@startuml
title Telemetry Api Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(Telemetry, "") {
  Container(TelemetryApi, "Telemetry Api", "Java, Spring", "")
  Container(TelemetryCache, "Device Management Cache", "Redis", "Cache for telemetry")
}

Container(TelemetryApi, "Web Application", "Java, Spring") {
  Component(TelemetryController, "TelemetryController", "Get current telemetry")
  Component(ServiceLayer, "Service Layer", "Get telemetry data")
  Component(RepositoryLayer1, "Repository Layer1", "Cache data access logic")
}

Rel(TelemetryController,ServiceLayer,"Calls business logic")
Rel(ServiceLayer,RepositoryLayer1,"Reads/Writes data")
Rel(RepositoryLayer1,TelemetryCache,"Reads/Writes cache data")
@enduml